name             't3stack'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures different stacks of typo3.org infrastructure'
long_description 'help with local cookbook development by providing local setupst'
version          '0.1.0'

depends 'openssl'
#depends 'site-forgetypo3org'
